// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB04fRulJsTwWl20fqZFxzT7DgI8KG2YSQ',
    appId: '1:303349712786:web:6e13549c6f2611d232234b',
    messagingSenderId: '303349712786',
    projectId: 'authentication05',
    authDomain: 'authentication05.firebaseapp.com',
    storageBucket: 'authentication05.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3XNc-gN6J8qYi8g5qcF4nsUwsMecxqm0',
    appId: '1:303349712786:android:316c0904e4ed8f0e32234b',
    messagingSenderId: '303349712786',
    projectId: 'authentication05',
    storageBucket: 'authentication05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtuj9JebtabeD8nKFVaVI7qPTdaemoahM',
    appId: '1:303349712786:ios:da6f7ee30111f9c632234b',
    messagingSenderId: '303349712786',
    projectId: 'authentication05',
    storageBucket: 'authentication05.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtuj9JebtabeD8nKFVaVI7qPTdaemoahM',
    appId: '1:303349712786:ios:e625b5285a8020fd32234b',
    messagingSenderId: '303349712786',
    projectId: 'authentication05',
    storageBucket: 'authentication05.appspot.com',
    iosBundleId: 'com.example.authentication.RunnerTests',
  );
}
